cat <<EOF > /root/ansible/git-install.yml
---
- hosts: all
  remote_user: ubuntu 
  tasks:
    - name: install pakage
      apt:
        name: git
        state: latest
      become: yes
EOF      
      
      
      
      
